import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  MailPlus,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  SendHorizontal,
  FileBarChart,
  LucideIcon,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Home,
  Settings,
  SunMedium,
  Trash,
  User,
  Users,
  User2Icon,
  UserX2Icon,
  X,
  Printer,
  Wallet,
  ShoppingCart,
  History,
  WalletCards,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  WalletCards: WalletCards,
  History: History,
  close: X,
  Home: Home,
  Users: Users,
  profile: User2Icon,
  Printer: Printer,
  FileBarChart: FileBarChart,
  Wallet: Wallet,
  SendHorizontal: SendHorizontal,
  mail: MailPlus,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  ShoppingCart: ShoppingCart,
  trash: Trash,
  posts: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  payment:ShoppingCart,
  check: Check,

};
